apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grc-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - deployment.yaml
  - statefulset.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: grc-platform
  managed-by: kustomize

commonAnnotations:
  description: "GRC Platform Backend"
  version: "1.0.0"

replicas:
  - name: grc-platform
    count: 2

images:
  - name: grc-platform
    newTag: latest
    newName: grc-platform

vars:
  - name: SERVICE_PORT
    objref:
      kind: Service
      name: grc-platform
      apiVersion: v1
    fieldref:
      fieldpath: spec.ports[0].port
  - name: MONGO_HOST
    objref:
      kind: Service
      name: grc-platform-mongo
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
