apiVersion: v1
kind: ServiceAccount
metadata:
  name: grc-platform
  namespace: grc-platform
  labels:
    app: grc-platform

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grc-platform
  namespace: grc-platform
  labels:
    app: grc-platform
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grc-platform
  namespace: grc-platform
  labels:
    app: grc-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grc-platform
subjects:
  - kind: ServiceAccount
    name: grc-platform
    namespace: grc-platform
